services:
  postgres-test:
    profiles: ["test"]
    <<: *postgres-base
    env_file: ".env"
    environment:
      - POSTGRES_HOST=postgres-test
    networks:
      - test

  app-test:
    profiles: ["test"]
    <<: *app-base
    entrypoint: ["scripts/start-test.sh"]
    build:
      context: ./
      args:
        ENV: test
    env_file: ".env_test"
    environment:
      - POSTGRES_HOST=postgres-test
    depends_on:
      postgres-test:
        condition: service_healthy
    networks:
      - test
      
networks:
  test:
