x-postgres-base: &postgres-base
  image: postgres
  restart: always
  healthcheck:
    test:
      - CMD-SHELL
      - pg_isready -U postgres
    interval: 3s
    timeout: 3s
    retries: 5
    
x-app-base: &app-base
  build:
    context: .
    dockerfile: Dockerfile
  restart: always
