x-postgres-base: &postgres-base
  image: postgres
  restart: always
  healthcheck:
    test:
      - CMD-SHELL
      - pg_isready -U postgres
    interval: 3s
    timeout: 3s
    retries: 5
    
x-app-base: &app-base
  build:
    context: .
    dockerfile: Dockerfile
  restart: always

services:
  postgres-dev:
    profiles: ["dev"]
    <<: *postgres-base
    env_file: ".env"
    environment:
      - POSTGRES_HOST=postgres-dev
      - PGPORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - ./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - dev

  app-dev:
    profiles: ["dev"]
    <<: *app-base
    entrypoint: ["scripts/start-dev.sh"]
    env_file: ".env"
    environment:
      - POSTGRES_HOST=postgres-dev
      - APP_PORT=${APP_PORT}
      - APP_HOST=${APP_HOST}
    volumes:
      - ./:/shopAPI/
    ports:
      - ${APP_PORT}:${APP_PORT}
    expose:
      - ${APP_PORT}
    depends_on:
      postgres-dev:
        condition: service_healthy
    networks:
      - dev

volumes:
  pgdata-dev:

networks:
  dev:
