x-postgres-base: &postgres-base
  image: postgres
  restart: always
  healthcheck:
    test:
      - CMD-SHELL
      - pg_isready -U postgres
    interval: 3s
    timeout: 3s
    retries: 5
    
x-app-base: &app-base
  build:
    context: .
    dockerfile: Dockerfile

services:
  postgres-dev:
    profiles: ["dev"]
    <<: *postgres-base
    env_file: ".env"
    environment:
      - POSTGRES_HOST=postgres-dev
      - PGPORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - ./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - dev

  app-dev:
    profiles: ["dev"]
    <<: *app-base
    entrypoint: ["scripts/start-dev.sh"]
    env_file: ".env"
    environment:
      - POSTGRES_HOST=postgres-dev
      - APP_PORT=${APP_PORT}
      - APP_HOST=${APP_HOST}
    volumes:
      - ./shopAPI/:/shopAPI/shopAPI
      - ./alembic/:/shopAPI/alembic
      - ./scripts/:/shopAPI/scripts
      - ./main.py:/shopAPI/main.py
    ports:
      - ${APP_PORT}:${APP_PORT}
    expose:
      - ${APP_PORT}
    depends_on:
      postgres-dev:
        condition: service_healthy
    networks:
      - dev

  postgres-test:
    profiles: ["test"]
    <<: *postgres-base
    env_file: ".env"
    environment:
      - POSTGRES_HOST=postgres-test
    networks:
      - test

  app-test:
    profiles: ["test"]
    <<: *app-base
    entrypoint: ["scripts/start-test.sh"]
    build:
      args:
        ENV: test
    env_file: ".env_test"
    volumes:
      - ./shopAPI/:/shopAPI/shopAPI
      - ./alembic/:/shopAPI/alembic
      - ./scripts/:/shopAPI/scripts
      - ./tests/:/shopAPI/tests
      - ./pytest.ini:/shopAPI/pytest.ini
    environment:
      - POSTGRES_HOST=postgres-test
    depends_on:
      postgres-test:
        condition: service_healthy
    networks:
      - test
      
volumes:
  pgdata-dev:

networks:
  test:
  dev:
